### ISSUE TITLE
gtp_parse.py error

### ISSUE THREAD

**Issue by snayfach** [zjshi/gt-pro#33]
$ python3 scripts/gtp_parse.py --dict variants_main.covered.hq.snp_dict.tsv --in SRR413665_2__gtpro__20190723_881species.tsv.gz --v2
Traceback (most recent call last):
  File "scripts/gtp_parse.py", line 110, in <module>
    main()
  File "scripts/gtp_parse.py", line 105, in main
    gtp_array = read_gtp_out(gtp_fpath, args['ver_2'])
  File "scripts/gtp_parse.py", line 23, in read_gtp_out
    for line in fh:
  File "/usr/common/software/python/3.7-anaconda-2019.10/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by zjshi** [comment]
The input file need to be decompressed first to parse.
