### ISSUE TITLE
build database

### ISSUE THREAD

**Issue by Alice-yyt** [zjshi/gt-pro#46]
Hi Jason, I am sorry to bother you. When I run the ./GT_Pro build --in test/build.list --out ./test/my_db --dbname tri_db --threads 4, I got following errors. Do you know why I got those errors? Thank you for time!
<img width="892" alt="Screenshot 2022-03-08 at 3 27 51 PM" src="https://user-images.githubusercontent.com/42059758/157187721-11c46e48-6014-47c8-ac44-e142b3e0de27.png">

**Comment by zjshi** [comment]
Hi Alice-yyt, sorry for my late response. Would you please paste here the content of one of the log files, e.g. ./test/my_db/temp/ss_kmers/100001.ss.hq.log?

**Comment by Alice-yyt** [comment]
> Hi Alice-yyt, sorry for my late response. Would you please paste here the content of one of the log files, e.g. ./test/my_db/temp/ss_kmers/100001.ss.hq.log?

Hi Jason, thank you for your reply! Following are the contents in 100001.ss.hq.log:
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0196 Encrypted checksum: no encryption key specified
db_dump: BDB0210 ./test/my_db/temp/ss_kmers/100001.ss.hq.bin: metadata page checksum error
db_dump: BDB5115 open: ./test/my_db/temp/ss_kmers/100001.ss.hq.bin: Invalid argument

Thanks again!

**Comment by zjshi** [comment]
Thanks Alice-yyt. Unfortunately, I was not able to reproduce the issue you faced. Could you please also let me know which OS did you run the program as well as type in `ls -l ./test/my_db/temp/ss_kmers/` and paste the output here?

**Comment by Alice-yyt** [comment]
> Thanks Alice-yyt. Unfortunately, I was not able to reproduce the issue you faced. Could you please also let me know which OS did you run the program as well as type in `ls -l ./test/my_db/temp/ss_kmers/` and paste the output here?

Thank you for your reply! My OS is CentOS Linux release 7.6.1810 (Core). And here is the output of ls -l ./test/my_db/temp/ss_kmers/. Thank for your help!
<img width="887" alt="Screenshot 2022-03-30 at 1 54 33 PM" src="https://user-images.githubusercontent.com/42059758/160760987-7addd722-4c86-4e47-80be-758cfbf616a8.png">
.

**Comment by zjshi** [comment]
Hi Alice-yyt, thanks for posting output of `ls` but could you please do `ls -l`. So I was mainly wondering whether the intermediate files are empty before the final database building.

**Comment by qbdong122** [comment]
Hi Jason, I am sorry to bother you. I  wonder to know how to get the "msa.fa" and "core_snps.vcf" files before building my own database, because the _CallM_ doesn't work well so I had to try Mummer4, but I can not get these files directly.

**Comment by zjshi** [comment]
Hi qbdong122, thanks for trying GT-Pro and CallM. Using the CallM would be the easiest way to build a customized database for GT-Pro, since that is one of the purposes of CallM. Are your experiencing any issues with CallM? I would be happy to help with troubleshooting CallM.

**Comment by qbdong122** [comment]
Thank you very much! 
When I run CallM, i only get this 
....
[clustering] done
Traceback (most recent call last):
  File "/Business/NJMU_company/njmu-staff/soft/CallM/bin/CallM.py", line 1239, in <module>
    main()
  File "/Business/NJMU_company/njmu-staff/soft/CallM/bin/CallM.py", line 1230, in main
    call_snps_main(args)
  File "~/soft/CallM/bin/CallM.py", line 1116, in call_snps_main
    site_assembly = msa.monolithic_parse(args['msa_path'], args['msa_type'], args['max_samples'])
  File "~/soft/CallM/bin/align_io/msa.py", line 17, in monolithic_parse
    return parse_control(msa_path, msa_type, max_sample)
  File "~/soft/CallM/bin/align_io/msa.py", line 14, in parse_control
    return parse(msa_path, max_sample)
  File "~/soft/CallM/bin/align_io/xmfa_mummer4_io.py", line 30, in parse
    cur_aln.ncols = len(cur_aln.seqs[0].seq)
IndexError: list index out of range

**Comment by lvxsen** [comment]
> Hi Alice-yyt, thanks for posting output of `ls` but could you please do `ls -l`. So I was mainly wondering whether the intermediate files are empty before the final database building.

Hi Jason, I am sorry to bother you. I got the same error as Alice-yyt. Here is my output of ls -l ./test/my_db/temp/ss_kmers/. Could you please give me some advice?
![image](https://user-images.githubusercontent.com/69240152/168034335-9006e635-28cb-4efb-9a7e-d7fc5a15337f.png)

**Comment by qbdong122** [comment]
Hi! When I run CallM, the _tag_msa.fna_ file was empty, like this 
=
=
=
=
=
=
=
=
=
=
=
=
=
Why?



> Hi qbdong122, thanks for trying GT-Pro and CallM. Using the CallM would be the easiest way to build a customized database for GT-Pro, since that is one of the purposes of CallM. Are your experiencing any issues with CallM? I would be happy to help with troubleshooting CallM.

**Comment by qbdong122** [comment]
@zjshi Hi, When I run CallM, the output file _tag_msa.fna_ wae empty, like this 
=
=
=
=
=
=
=
=
Why? #

> Hi qbdong122, thanks for trying GT-Pro and CallM. Using the CallM would be the easiest way to build a customized database for GT-Pro, since that is one of the purposes of CallM. Are your experiencing any issues with CallM? I would be happy to help with troubleshooting CallM.

**Comment by qbdong122** [comment]
I get the same error, you have solved this?
> Hi Jason, I am sorry to bother you. I got the same error as Alice-yyt. Here is my output of ls -l ./test/my_db/temp/ss_kmers/. Could you please give me some advice? ![image](https://user-images.githubusercontent.com/69240152/168034335-9006e635-28cb-4efb-9a7e-d7fc5a15337f.png)

**Comment by lvxsen** [comment]
> I get the same error, you have solved this?
> 
> > Hi Jason, I am sorry to bother you. I got the same error as Alice-yyt. Here is my output of ls -l ./test/my_db/temp/ss_kmers/. Could you please give me some advice? ![image](https://user-images.githubusercontent.com/69240152/168034335-9006e635-28cb-4efb-9a7e-d7fc5a15337f.png)

Sorry, I haven't solved this problem yet.

**Comment by zjshi** [comment]
Happy to help! Could you either of you share the genomes sequences used for the database building as well as the following files: `reference.fna`, `msa.fa`/`tag_msa.fa`, `core_snps.vcf` and `coords.tsv`? I would like to start an investigation of this issue by reproducing the error at my end. Thanks.

**Comment by qbdong122** [comment]
> Happy to help! Could you either of you share the genomes sequences used for the database building as well as the following files: `reference.fna`, `msa.fa`/`tag_msa.fa`, `core_snps.vcf` and `coords.tsv`? I would like to start an investigation of this issue by reproducing the error at my end. Thanks.

I use the test/ data and follow these commands:
_tar xzvf test/100035.tar.gz && tar xzvf test/101747.tar.gz && tar xzvf test/102779.tar.gz_
_./GT_Pro build --in test/build.list --out ./test/my_db --dbname tri_db_ 
then I get these error

**Comment by aababc1** [comment]
Hello zjshi . Thank you for your nice tool. 
like other people, I tried to build database using gt-pro, but I encountered similar errors with others. 
Error: the following returned non-zero status: 'db_dump ./test/my_db/temp/ss_kmers/100001.ss.hq.bin 1> ./test/my_db/temp/ss_kmers/100001.sckmer_allowed.tsv 2> ./test/my_db/temp/ss_kmers/100001.ss.hq.log':

b''

Error: the following returned non-zero status: 'db_dump ./test/my_db/temp/ss_kmers/100002.ss.hq.bin 1> ./test/my_db/temp/ss_kmers/100002.sckmer_allowed.tsv 2> ./test/my_db/temp/ss_kmers/100002.ss.hq.log':

b''

Error: the following returned non-zero status: 'db_dump ./test/my_db/temp/ss_kmers/100003.ss.hq.bin 1> ./test/my_db/temp/ss_kmers/100003.sckmer_allowed.tsv 2> ./test/my_db/temp/ss_kmers/100003.ss.hq.log':


I don't know which tool(installed by conda or else) contains it, but I think this error is related with the db_dump  version (Berkeley DB tool )  .

Can you inspect it ?   
Thank you zjshi
